language: scala
scala:
- 2.11.2
script:
- sbt ++$TRAVIS_SCALA_VERSION "compile" "publishOnlyWhenOnMaster"
jdk:
- oraclejdk8
env:
  global:
  - SCALAMETA_MAVEN_REALM="Sonatype Nexus Repository Manager"
  - SCALAMETA_MAVEN_DOMAIN="oss.sonatype.org"
  - secure: JRzafKs6rGViD2Tn03ApYHwmYsiDD+sRyy9hZu3CZDhpVWa8nB3oLSqwHJZBUD8596TYKjF5pBjXXazmiICDZ468LH+OXAE8MmIoXnk1xWSBiR8PVZlYYIixOamCfgu6dwAIYSJ+ThKZqzQZyHYVFsrWpxshVpI2Gl+nuqE8NdutO3YuZ7lxUDqt6GogCcRWB1690jLx+uh56VWYevk7DFKPxpClZI4s/8tOqVvtCFfae4C5OWT7UZmGmgCiHqia5Fxuz0hR9MJXe3MZJzGDuzCBP5lUaTyvRqxjF3Dvqq6rQVL4UPlIdYY2smA+4laHsWxBFjRsZW3Pa9IPcZFL31IhzjXxkNB9iKlybI1fD704EgNid7+HxDCLRW1iIBiRPxtF/vPCeRgAw7aDRJNzEqO84CjjvVuo0885uUICaQRilRRO7Nxe46MuzdoOrLNX7hhpC7frr3tUagEip16YepGC2nIwQ+1nxmK9c1julG8pJDgKV2BzTzwUrx7vUiPRd7jjP+TeOybrMnA6J7GcBkJ/W4XlDZObd7zrHXZWdVYXr/AIBLUpNrvCRw08T/9POK5QtVLDi52E23kxGNWILmsajrrt1aj63+4zrkITAvY+xfqi69ew5Aa1t+u0iqDaIRsbIrFugh2RuNMvfQ5hiPIjR8CqPIKHNWsmn9RcSXI=
  - secure: ICcLUg34njUF155n11Sxw+2nSGiwameTiY5BSz4MzHqr5wMWe6jui6sS9efZYlfAPjWBVugKKOBgL5bd9CHIAqYSN4txMyVolZ8LVXa/8bT9+GLrf+qKsavm8mhuTtIdlu03YjNF56TdfTywpA8mvlXJHjUr+owYBBRPxJrDA3SbLIs/ZUEW5f3ZgiNDWH1o2/PHbk9mMBaP6xCTvGwoXbSMYoA9WzYftZp7WPgQ8KASX4aSFNOg81yCOd5zZ2vzC9jfoK3grzng0xAioMFtr9Cs72N6euc+y4IcG9hFQRCrT7Kv2b1itK1cyJa3wR7p/omp2XBJJlHqXssvQew7wUpOvkdy6HHSFAdQ2Q6ef8+UFca74vDiFeQYqGi9nQAK3N7iGadiw/Fk9GspqRBiPFK4QXLtwifszWq1OYxWxFnyMh1EOWNXwh0GVk5ARWSCZ447cpIhtBDcZW+jP+pdyZbkRSLT1k/WQKAklD/z+9ko9MJPZVNQgvQsj3873DB5HRkEPY5IUo17X9UdCANY5H/Qtvq5ee5uCZY72ybj/SWgB/8copUjxFP+lK2tFRaokQeTKk30AJ+e9OAEO/9VwDAHv9BN28RC1bKAjINMps1BikkvEbV/AZcva9FBzpshfE5rgOKr+QBjh1FXesrhJB6p4Bk2iyVmuIhiaDYGcuo=
