language: scala
scala:
- 2.11.2
script:
- sbt ++$TRAVIS_SCALA_VERSION "compile" "publishOnlyWhenOnMaster"
jdk:
- oraclejdk8
env:
  global:
  - SCALAMETA_MAVEN_REALM="Sonatype Nexus Repository Manager"
  - SCALAMETA_MAVEN_DOMAIN="oss.sonatype.org"
  - secure: Xmglkt5r3D1FJGCm3NstfnbZCoomIOI+ElQWHat50xGVTY+rdjiWXwlorHTwEGPdfDrhOZErVDSmy2W3C//EmLLsMVSkLXeCFq2d/vJknh7YUk7uCcu9LDnzMKYoptYit9/lOFJv6zCOUQsLwwb0HJaCLWurAyvYmhYqqdXeTTOl84lym80qfcdovr6pIvdgmBFEg63h7ZLq7bzxT9YhrzKjXtjMkI+liSaZNQO4HiiwDuTouDW84iGA22sjHsAy4hFrumHg3yEKSE/X5+p4av1LWuZl88Jks8elBEhe+2mKzciOGbTKMoCDZ6cFaClwd039PKjXapBZsXMfGGjmETPm09kH7z5YceIY/zAooSHpHh7XqzH+T5wjvc7qcgZlndF/apqIa6Y0Oz40srCtbDN+ffLPu3Ny9ALKbyA6c3YvwahzzCJt7MGxChT9r5th9pL6SaLlQKhxcW4UbRK61mwplXSoDjwnvcCNWHbRQ/LIjok4wQdSi31HlwkHyWwhb694YTm50q8owMbpA626/gu65TKMh+xsdGVr5m2r7gP2oRp24XbWa95xOM2kiUyn2SEC1voRCZ0cPFTpR8OXwWHf49YJiZnLWMzIXCBIlAdFyn1haI4oozLRuMzM0n9m/9y8p+kXORm5Iv8ZmBKs+u3dOcFE7wkGfmf+FJMe0zU=
  - secure: i+Fx/wTltbafjbDa/1PbBFor/tQPM6MvGh0+0+njyAXdTnv+ABJA9S7nOoXp0Z7GQ6J2uoUJFmS7ZE0XV6T4AR6ntRqlGk2mRXqlLespAUysFNC9N7mTcauS4nWhPTmcYtcXcKVHZICv5+l3xubVI2u4j+F474uv1zQkR8yioS8QUGLpmfuKdZUkBTybkgtVvFA6Q1WyJoPyaFeVdpKhU2KYirjAQFrcacYhur4L8eH4+tyPttYIV5jE6eT/l3Sv9PU4rNa1mbgAnXRi9KHCvRqBUfC64zdLXWD2D19Rc8UizV3ZKZG70byu6dCrtDK3DF9qCrbz1mZQQecooC0ob9oLIQClfJV2DVI2c0xkTR96N/V2gRJKlJwVceEy3OnHHCJAMbtprjclI7vpRCuQ88kj4Mx4ZZsgHFmj/XQ32Ds8BtoiSlNjJPu4F41lNrtUcqOq54w2bJBd084j9mzRzeCKUgFoNdeAGEMSIs1pOWofVjFfvEsxDDu6MchuR2S6+QT5mSz57mw8kiHrCeMEitbT2PnDkfzDuajjSfDv+wD2zmLXz1MgKEF1+WSNiiT5uzLwV6P68JcjPQi7CDWL1J/yXsIgLp3vhcdCe1AiTduqW5klVphIhh43otJpOwLHluOgQO7b8v1n7UX6gykvtSlfZdji+INdpJ35HmZy0T8=
